name: safety_eta
description: Safety ETA
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  animate_icons: ^2.0.0
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.0.2
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  date_time_picker: ^2.1.0
  dotted_line: ^3.1.0
  dropdown_button2: ^2.0.0
  elegant_notification: ^1.8.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.0.2
  flutter_reorderable_list: ^1.3.1
  flutter_smart_dialog: ^4.9.0+6
  flutter_switch: ^0.3.2
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  just_the_tooltip: ^0.0.12
  loading_animation_widget: ^1.2.0+4
  multiselect: ^0.1.0
  neopop: ^1.0.2
  nested: ^1.0.0
  number_paginator: ^0.2.3
  phosphor_flutter: ^1.4.0
  star_menu: ^3.1.4
  strings: ^0.2.2
  syncfusion_flutter_charts: ^21.2.4
  syncfusion_flutter_datagrid: ^21.2.6
  syncfusion_flutter_datepicker: ^21.2.3
  uuid: ^3.0.7
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - envs/env.dev
    - envs/env.uat
    - envs/env.production
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 300
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
