import 'package:flutter/material.dart';

Color darkTeal = const Color(0xff252b36);
Color lightTeal = const Color(0xfff1f4f9);
Color grey = const Color(0xffd1d5db);
Color darkGrey = const Color(0xff454b54);
Color primaryColor = const Color(0xff0c83ff);
Color textColor = const Color(0xff1F2937);
Color primaryHoverColor = const Color(0xff0b76e6);
Color successColor = const Color(0xff059669);
Color successHoverColor = const Color(0xff059669);
Color warnColor = const Color(0xfff58646);
Color warnHoverColor = const Color(0xffdd793f);
Color dangerColor = Colors.red;
Color purpleColor = const Color(0xff8e70c1);
Color purpleHoverColor = const Color(0xff8065ae);
Color lightGreen = const Color(0xff3fdca5);
Color lightGreenAccent = const Color(0xffecfadc);
Color lightRed = const Color(0xffef556d);
Color lightBlue = const Color(0xff00bef6);
Color lightBlueAccent = const Color(0xffD0EFFF);
Color darkGreyAccent = const Color(0xff898989);
